### ISSUE TITLE
jaasLogin: FAILED, LoginException: No LoginModules configured for pam

### ISSUE THREAD

**Issue by gordonwoodhull** [s-u/SessionKeyServer#7]
Hey @s-u, how is the other side of the world?

I'm helping @robert-a troubleshoot his rcap2 instance. Login fails with the above message printed to the log. The machine used to work but was rebooted.

I know this is not an SKS issue per se. I don't (yet) understand how JAAS gets its default configuration. 

Thought you might know offhand; if not I'll keep digging, and post an answer if I find one. Probably a good thing to have documented here on GitHub.

**Comment by s-u** [comment]
jaas is not used and should not be used. It should be using the PAM module instead. It all makes no sense, so I'm wondering if something broke in the system. If in doubt, run `make pam`. Also note that rcap2 is not using NIS so see https://github.com/att/rcloud/wiki/Deployment#pam-and-sks

**Comment by robert-a** [comment]
Ran make pam but no change.

rcap2:/data/rcloud/services/SessionKeyServer$ make pam
make: Nothing to be done for 'pam'.

**Comment by s-u** [comment]
Just to explain - SKS tries all available sources until it succeeds and the last source is JAAS which is why the error message mentions it. However, in Robert's setup the intention is for PAM to succeed, so the first step is to check the system logs for PAM login attempts and any errors. As I noted above in a local setup you must make sure that user running SKS can authenticate - see the link above.

**Comment by gordonwoodhull** [comment]
Thanks @s-u, I see that @robert-a has fixed it based on your advice.

This explanation was really helpful.

To document what we learned here: the error message was deceptive because SKS was trying to be helpful and permissive in trying JAAS, but this is after PAM failed, the error that actually interested us.

In our case `key.db` needed needed to be readable by the group of the user running the SKS service.
